- README.rst
Sorry, more formatting errors. Should all be fixed now!
> Update README.rst formatting

- README.rst
- algorithms/README.rst
- index.rst
- tags.rst
- workflows/README.rst
Fixed some Restructured Text syntax errors
Added section for tagging notebooks
> Structure cleanup for docs publishing

- algorithms/RandomForestClassification.ipynb
> Update heading markdown as suggested by issue #14

- algorithms/DEAPlotting.py
Importing DEAPlotting as a module was failing due to a "TabError" (both tabs and spaces used for indenting); fixed this by replacing with spaces
> Fix "TabError" bug in three_band_image

- tags.rst
Added "* Above the cell, change **Code** to **Raw NBConvert**"
> Close issue #40 by adding missing step to documentation

- algorithms/SpatialTools.py
Changes to make function adaptable for Chad's workflow; also fixed up docstrings to make them easier to read (following format used by Josh Sixsmith)
> Updated rasterize_vector to produce binary array if no shapefile field supplied

- Scripts/DEAPlotting.py
Plots now plot with the correct coordinates, allowing them to be combined with other spatial data.
I've also explicitly included the 5000 reflectance standardization as a parameter, because my plots always come out far too dark.
I've tested this on a few datasets and everything seems to be working without breaking older code.
> Refactor three_band_image to fix coordinates bug; add optional contrast stretch

- Scripts/ClassificationTools.py
layer_extent, rasterize_vector and  array_to_geotiff are all in SpatialTools now
> update scripts locations to SpatialTools

- README.rst
Introducing referencing  standards to our standard readme ! :) 
- link to GA ref guide
- need to also add examples
Bex
> Include referencing suggestions

- DEA_datasets/TestNotebook.ipynb
> Test of direct upload alternative to git

- DEA_datasets/TestNotebook.ipynb
Whoops, need to test with a file that is actually different
> Second test of overwriting file with actually different file

- README.rst
Displaying widgets in Jupyter Notebooks section added (check it out! NBViewer for  the win!)
> update README with info on displaying widgets on github

- Scripts/DEAPlotting.py
- Scripts/README.rst
Takes two single-timestep xarray datasets, and plots an animation of the two layers fading between each other. Possible applications include comparing an area before and after environmental change (i.e. flood, drought, fire, development), or comparing two geographic areas.
+ Minor changes to default values
> Add new animated fade function

- Scripts/DEADataHandling.py
This makes the function more flexible by allowing you to control the PQ values that are used to calculate the percentage of clear values per season. For example, you could choose to use only one of the two cloud masking algorithms (e.g. to prevent misclassified snow from affecting filtering).
> Allow load_clearlandsat to accept custom PQ masking criteria

- Scripts/DEADataHandling.py
Prevents nodata gaps in resulting animations.
> Use NBAR rather than NBART in load_clearlandsat

- README.rst
Change headings to level 2, so that they don't get added to the index on the website.
> Change the heading levels

- Scripts/DEADataHandling.py
- Scripts/DEAPlotting.py
Added:
- New function for plotting side-by-side animations
- Can now plot either three band or one band images
- Customisable title and date annotations
- Customisable colour schemes
Example showing NDVI and NDWI animated side-by-side with custom colour schemes and title for each panel:
> Add new animation functions

- Scripts/DEADataHandling.py
As 'rasterstats' package is not a default DEA module, zonal_timeseries functions is commented out.  Do not accept this pull request until rasterstats has been installed and function has been uncommented.
@BexDunn @CEKrause
> Add function for calculating zonal statistics

- DEA_datasets/README.rst
Updated FC notebook removed old one from index
> update readme to remove old NB

- Scripts/DEADataHandling.py
auto_combine doesn't have an option to preserve attributes, so we lose our crs objects
> Changing back from auto_combine to concat

- Scripts/TasseledCapTools.py
including threshold and pct exceedance functions for Hovmollers and regional areas
> Tasseled cap tools scripts

- Temporal_analysis/Hovmoller_NDVI_Multi-site.ipynb
- Workflows/Fractional_Cover_Change_Detection.ipynb
Fix heading so title appears in ToC here: 
http://geoscienceaustralia.github.io/digitalearthau/notebooks/Workflows/README.html
> Fix FC trends heading

- Scripts/ClassificationTools.py
INEGI had some problems due to hard-coded Aus Albers coordinates and categorical/string classes in shapefiles. Have updated to work for any projection system, and added system for re-mapping strings to integers
> Update randomforest_train to be more flexible for non-Aus

- 10_Scripts/DEAPlotting.py
- 10_Scripts/README.rst
Are you sick of irritating colourbars? Wish someone would write a function so you don't have to worry about it? Well, hopefully this is that function...
> Adding wofs plotting function to DEAPlotting

- 10_Scripts/DEADataHandling.py
Production database has been updated to use new defaults vs when function was written
> Update load_clearsentinel to use production database defaults

- 10_Scripts/DEADataHandling.py
- 10_Scripts/README.rst
Added reproducible example and first doctest: running the script driectly (`python DEADataHandling.py`) will now use doctest to test the example included for load_clearsentinel2, and return an error if the function no longer returns data!
Also renamed load_clearsentinel to load_clearsentinel2, and fixed outdated print statement
> Add revised function with first doctest!

- 10_Scripts/DEADataHandling.py
Updating documentation to match new defaults
> One more minor update to documentation for load_clearsentinel2

- tags.rst
made the external link to the new tags index work again!
> Fix broken links to the tags index

- 10_Scripts/DEADataHandling.py
Second commit reverts accidental reverts to other people's changes
> Update documentation for load_clear* functions

- 10_Scripts/FileDialogs.py
- 10_Scripts/README.rst
FileDialogs.py has scripts to create buttons using widgets, so your notebook file selection works more like a gui.
> necessary script for running ipywidget drop down file selection dialogs

- 09_Workflows/Fractional_Cover_Percentiles.ipynb
This pull request updates the script paths in the Fractional_Cover_Percentiles notebook from Scripts to 10_Scripts
> fix issue #241 

- 02_DEA_datasets/Introduction_to_Fractional_Cover.ipynb
- 09_Workflows/Fractional_Cover_Percentiles.ipynb
Sorry - this PR changes the paths expanding your user directory to relative paths, so this should work for new peeps.
> actually fix #241

- 10_Scripts/DEAPlotting.py
- 10_Scripts/README.rst
Mentioned the wrong parameter name
> Fix minor incorrect documentation

- 11_UN_Sustainable_Development_Goal_indicators/11_6.6.1_Change_in_extent_of_water-related_ecosystems/11_6.6.1_Water_Wet_Veg_Workflow.ipynb
add UN SDGs directory and 6.6.1 draft workflow
> add UN SDGs directory and 6.6.1 draft workflow

- 04_Index_calculation/README.rst
- 04_Index_calculation/Tasselled_Cap_Wetness_Index_Calculation.ipynb
Added a TC wetness notebook. This notebook can calculate the tasselled cap wetness index for surface reflectance data for as many scenes as you like, then save the landsat data and tasselled cap data to geotiff.
> bex added TCI notebook

- 10_Scripts/TasseledCapTools.py
updating paths in the tasselled cap tools script
> update  10_Scripts/TasseledCapTools.py re issue #186

- 05_Temporal_analysis/Hovmoller_NDVI.ipynb
- 05_Temporal_analysis/Hovmoller_NDVI_Multi-site.ipynb
- 05_Temporal_analysis/Hovmoller_TCI_and_Rainfall.ipynb
Despite only one of these showing up in the search for 'Scripts' there were four notebooks with this issue.
> update paths in hovmoller notebooks re issue #186

- 10_Scripts/DEAPlotting.py
Also remove redundant kwargs.update({'aspect':aspect}) (this is automatically passed in without having to set the dict)
> Update remaining Scripts references in DEAPlotting 

- 08_Outputting_data/LandsatScenestoGeoTIFF.ipynb
- 08_Outputting_data/README.rst
Added the landsat to geotiff multiple scenes notebook I wrote for the hackathon
> Bex staging

- 08_Outputting_data/ExportingCompliantNetCDFs.ipynb
NetCDF functions moved to `datacube.drivers.netcdf`, and the sample files moved in Robbi's folders.
> Update notebook to use functions in NetCDF driver

- 02_DEA_datasets/Introduction_to_WOfS.ipynb
- 02_DEA_datasets/README.rst
Added the introduction to  WOfS notebook for our training day tomorrow
> adding Intro to WOfS notebook

- README.rst
'update the README.rst file in the directory'
Because I always forget this bit and new users do too
> Bold text the bit everyone misses

- 10_Scripts/tiledSegParallel.py
This is a customized version of the tiledsegsingle.py module implemented through RSGISlib.  It runs a tiled image segmentation in parallel across a specified number of cpus.
An example implementation of the module will be uploaded to '09_workflows'
> adding tiledSegParallel module to 10_Scripts

- 10_Scripts/SpatialTools.py
removing redundant parameter from documentation in geotransform
> update to geotransform function

- DEA_sandbox/Case_Studies/Intertidal_Elevation.ipynb
- DEA_sandbox/Case_Studies/utils/waterline_funcs.py
New notebook to demo to Qld gov at workshop this month.
For now, we're not worrying about tags and index files for `dea-sandbox` notebooks.
> Add new notebook for modelling intertidal elevation a la NIDEM

- 10_Scripts/DEADataHandling.py
Two new variables to 'load_clearlandsat':
- dask_chunking: add dictionary of dask chunks to allow for explicitly specifying spatial and temporal chunking
- lazy_load: adding boolean to allow for optionally delaying the computation of load_clearlandsat - facilitates easy parallel processing with dask
> adding explicit dask functionality to load_clearlandsat

- DEA_sandbox/Case_Studies/Agriculture.ipynb
- DEA_sandbox/Case_Studies/utils/casestudy_agriculture_functions.py
to make dynamic figures work in lab as well as notebook have to wrap them into
output widget.
Changing from `%matplotlib notebook` to `%matplotlib inline` as this is only
setting that works across lab and notebook
> Update to support jupyter lab

- DEA_sandbox/Case_Studies/utils/casestudy_agriculture_functions.py
`xr.plot.plot` resets titles, we want custom
> Fix titles in agriculture case study

- README.rst
Changed a few folders to have simpler names, and updated the README to reflect this.
> Directory restructure

- DEA-notebooks_template.ipynb
Adding the template notebook to the develop branch
I think this worked! Thanks @BexDunn and @caitlinadams for the advice.
> Add template to DEA sandbox repo

- .github/PULL_REQUEST_TEMPLATE.md
New pull requests from now on should have this template in this box when they are created for the user to edit. Feel free to suggest/apply changes to the wording and/or items.
> set up a preliminary pull request template

- Beginners_Guide/README.rst
- DEA_Datasets/README.rst
- Frequently_Used_Code/README.rst
- Real_World_Examples/README.rst
This commit is necessary to get the DEA docs working.
> Add descriptions to each folder's README.rst file

- DEA-notebooks_template.ipynb
- DEA_Notebooks_Template.ipynb
- move additional information to end of notebook
- add example packages to load, including sourcing the scripts directory
- add information on highlighting parameters to getting started section
- add guideline around using subheadings
- break up markdown paragraphs so each sentence is on a new line to aid git-diff in future
Leaving as a draft PR for now so people can comment and make any further changes.
> Update notebook template

- Scripts/dea_bandindices.py
> Make normalisation step optional for calculate_indices

- Scripts/dea_bandindices.py
Plus some minor formatting fixes
> Add MSAVI and NDCI to calculate_indices

- Scripts/dea_bandindices.py
> Fix AWEI water index formulas

- README.rst
Added a temporary list of useful resources to the readme to assist during the DEA refresh.
Will remove before we merge into master at the end of the refresh
> Add temporary resources for collection upgrade refresh

- Scripts/dea_datahandling.py
Have added a number of performance increases to the `load_ard` function:
- Thanks to @Kirill888 , the function now casts to `float32` instead of `float64` when masking invalid data. This decreases memory use by 50%.
- We no longer calculate the percentage of cloudy pixels per observation if `min_gooddata=0.0` (the default), because in this situation the user is happy to keep all observations regardless of cloud cover. This saves a significant amount of time for long time series loads, as we don't need to first load `fmask` arrays into memory to do the calculation
- Have swapped from `np.isin()` to xarray's built in `.isin` when testing `fmask`, which prevents `fmask` from being computed when lazily loading data
> Performance enhancements for load_ard

- Scripts/dea_classificationtools.py
An empty script to add functions used to classify remote sensing data (e.g. random forest, decision trees, k-means etc)
> Add placeholder dea_classificationtools script

- 10_Scripts/DEADataHandling.py
Same fix for missing CRS when changing dtype
> Same fix for lost CRS attributes for `load_clearlandsat`

- Scripts/dea_plotting.py
Currently the `rgb` function fails when an array with no 'time' dimension was specified. This was accidently caused by the way that the aspect is calculated, which currently tries to exclude the `index_dim` (e.g. `time`) to get the `x` and `y` dims. If there is no `index_dim` in the dataset, this will fail.
Changed to selecting the final two dimensions instead, which works regardless of whether `time` is in the dataset.
> Close #393 by calculating aspect on the final two dimensions, rather than excluding the sometimes missing index_dim

- DEA_sandbox/Tutorial/02_Do_It_Yourself.ipynb
- DEA_sandbox/Tutorial/utils/dea_plotting.py
- fix the issue with axis ticks and replace three_band_image with rgb
- update text throughout
- leave all variables blank for the user to supply, with suggestions in markdown
- use time_step to select the same image in all plots
- add a hint about how to change the colourmap in the NDVI section
> Updates to DIY notebook

- Scripts/dea_bandindices.py
- adds option deep_copy=True
- sets index to list automagically
- calculates all indexes input as a list
- added documentation explaining the behaviour of deep_copy and drop
- calculates multiple indexes!!!
deep_copy=True is necessary to prevent the drop option from modifying the input dataset due to xarrays default behaviour to shallow copy e.g. modify Datasets and DataArrays in place.
- Closes Issue #375
> improve dea_bandindices to calculate multiple indexes

- Scripts/dea_datahandling.py
- Add notebook showing how to create and apply masks
> Notebook demonstrating cloud masking

- Scripts/dea_coastaltools.py
Modified tidal tag function to add tidal phase calculation.
This allows the user to estimate whether each satellite image was acquired during ebb or flow tides using `ebb_flow=True`. This information is added as a new variable in the dataset.
> Add tidal phase calculation to tidal_tag function

- Frequently_used_code/Geomedian_composites.ipynb
Datacube stats has been installed on the Sandbox, so this notebook has been updated to reflect that. Also checked for sphinx known-issues and edited markdown.
> notebook now works on Sandbox, edited to reflect this

- 10_Scripts/DEADataHandling.py
Added a conditional statement to the load_clearlandsat function to avoid computing good-quality pixel percentages if they are not needed. This avoids performing sums across dask chunks if chunking is used in spatial dimensions so it is faster.
> Skip pixel quality percentage computation if not needed (way faster if using dask chunks)

- 09_Workflows/LinearModels-NDVI_recession.ipynb
Removed variable that was no longer required and updated metadata
> Updated linear recession script

- Scripts/dea_classificationtools.py
Include a brief description of the changes being proposed, and why they are necessary.
- [X ] Remove any guidance cells (e.g. `General advice`)
- [X ] Ensure that all code cells follow the [PEP8 standard](https://www.python.org/dev/peps/pep-0008/) for code. The `jupyterlab_code_formatter` tool can be used to format code cells to a consistent style: select each code cell, then click `Edit` and then one of the `Apply X Formatter` options (`YAPF` or `Black` are recommended).
> Classificationtools

- DEA_sandbox/ARD_Intercomparison/settings/LS8_GA-LAM_USGS.cfg
- DEA_sandbox/ARD_Intercomparison/settings/LS8_GA-NBART_USGS.cfg
- DEA_sandbox/ARD_Intercomparison/settings/LS8_GA-NBAR_USGS.cfg
- DEA_sandbox/ARD_Intercomparison/settings/LS8_GA-all_USGS.cfg
Minor changes to the ARD intercomparison tools.
> ARD intercomparison tools notebook niceness

- README.rst
Added a temporary header to the main readme which will direct users to master_archive if needed
> Add temporary header to readme pointing to master_archive branch

- Real_world_examples/README.rst
Add water classification notebook, updated to reflect required `develop` branch style.
> Water classification notebook

- Real_world_examples/Mining_rehabilitation.ipynb
- Real_world_examples/README.rst
- Scripts/notebookapp_miningrehab.py
Addition of the mining notebook in the new style
> Mining rehabilitation notebook overhaul

- .gitignore
- Scripts/README.rst
- Supplementary_data/README.rst
Minor fixes required before overhaul commences. Known tasks:
> Pre-merge patch for develop

- Scripts/dea_spatialtools.py
this PR fixes two bugs and one minor issue:
1. The `export_geotiff` variable would fail if the array didn't have a crs attached. Also, the known xarray bug that removes attributes when converting to a dataset is now handled. 
2. Re-projection of the geodataframe,  `gdf_reproj = gdf.to_crs(crs)`, would fail when the crs object was a `datacube.utils CRS` object. The code now converts the crs to a string to avoid this. 
3. The error messages for not providing a transform object confusingly asked the user to provide a 'affine' parameter, when the function definition requires a `transform` parameter. This has been amended in `xr_vectorize` as well.
> fix bugs in xr_rasterize

- Scripts/dea_plotting.py
Close quotations so the code works
> Close quotations on line 413

- Scripts/dea_datahandling.py
Came across an unexpected issue where running `load_ard` twice produced a dataset with different bands. This turned out to be because of the way loading `fmask` and `contiguity` data was handled: the function inserts them into the `measurements` to load if the user doesn't supply them (and later removes them from the dataset so the user never sees them). 
Turns out that if `measurements` is supplied as a `**query` kwarg, the external `query` object is also modified permanently (despite being outside of the function), meaning the next time the function is run, the extra measurements are included in the data load despite the user never asking them to be loaded.
Have fixed by creating a deep copy of the `**dcload_kwargs` object, so any measurements inserted into the query don't get inserted …
> Fix small bug where load_ard produced different results each run

- Beginners_guide/README.rst
Add missing beginner's guide notebooks to index file so they can be rendered in user guide
> Add missing beginner's guide notebooks to index

- Scripts/dea_temporaltools.py
A module for time-based scripts is added to the scripts directory. These scripts are used in some of the WIT notebooks and a notebook for 'frequently used code snippets' that I'm hoping to push up today. 
I anticipate that we'll add more scripts to the module, hopefully around capabilities like 'find nearest timestep and retrieve data'.
> made a module for temporal tools for notebooks

- DEA_notebooks_template.ipynb
- Scripts/dea_datahandling.py
This is a pull request to test out two new apps that have been added to the DEA Notebooks repository: 
* ReviewNB: https://www.reviewnb.com/
* This will allow us to finally view detailed diffs for notebook changes, which should make reviewing notebooks easier
* Pep 8 Speaks: https://pep8speaks.com/
* This will give us immediate feedback on PEP8 compliance for code pushed to the repo
Hopefully these two apps will show up in the comments once it is posted!
> Test new Github apps with minor updates to template

- Spatial_WIT/spatial_wit.ipynb
An initial version of spatial wit
N/A
> init spatial wit

- Spatial_WIT/spatial_wit.ipynb
- Add spatial wit function
- Clean up
N/A
> add spatial wit function

- README.rst
Update readme to give example of how to check out a PR branch, and make edits directly.
Also change `master` to `develop` in final paragraph.
NA
> Add git commands for checking out a branch during a PR review

- Scripts/dea_spatialtools.py
Tiny change: added a verbose flag to `dea_spatialtools.subpixel_contours` so you can suppress the debugging messages.
Sorry for the email spam. >.>
> Added verbose flag to subpixel_contours
