- algorithms/DEADataHandling.py
Now when you load surface reflectance data, the function will only filter nbarT for -999 terrain values and will only tell you that it has done so if it did-
there is a new loop that tests to see if the product is nbar or nbart before printing that data is loaded and filtered.
> updated string and filter to correctly apply to nbarT vs nbar

- algorithms/DEADataHandling.py
Selecting bands using `bands_of_interest` in load_nbarx should now work work correctly; the default is to now select all bands. The code had an existing `if bands_of_interest:`, so this change shouldn't break anyone's code after all.
The other thing I've changed is the name of the variable `filter_clouds`. As it's currently set up, the PQ mask currently masks both clouds _and_ saturated pixels, so I've generalised it to `filter_pq` which better describes what it does. Unfortunately this will break code if people have specifically set `filter_clouds = True` or `filter_clouds = False`, but hopefully most have just used the default value so it won't affect them.
> Revise load_nbarx to work when selecting bands, rename filter_clouds to filter_pq

- algorithms/SpatialTools.py
Added new reproject_to_template function for reprojecting a raster into the extent, cell size, projection and dimensions of another raster
> Add reproject_to_template function to SpatialTools

- algorithms/README.rst
Possible way to have some basic documentation of functions in Algorithms: simply update the readme file with a list and basic descriptions of the functions. This could be an easy intermediate step until we work out a more automated function documentation
I'm not sure if this will affect the existing automated .rst import
> Added function documentation to Algorithms .rst file

- Scripts/DEAPlotting.py
Removes `Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).` warning
> Add clip to plotting function to remove warning message

- Scripts/DEADataHandling.py
- Scripts/DEAPlotting.py
`load_clearlandsat` loads cloud-free Landsat time series, and `animated_timeseries` plots them as an animated .gif or .mp4 with a date annotation:
> Add new functions for plotting DEA data as cloud-free animations

- Scripts/DEADataHandling.py
Andrew, can you please check that we are now handling nodatavalues correctly for sentinel? We've realised that we were not handling them correctly for landsat as we had assumed only NBART had -999.0s
This pull request should fix this in our 3 loading functions (load_nbarx, laod_sentinel, load_clearlandsat, )
Thanks!
> fixes to nodatavalue filtration in 3 fns

- README.rst
A bunch of subheadings are still appearing on the website: http://geoscienceaustralia.github.io/digitalearthau/notebooks/index.html
This time use "~" for subheadings? (Not sure if this will work)
http://docutils.sourceforge.net/docs/user/rst/quickstart.html
> Second attempt at trying to fix headings copying across to website

- Scripts/BandIndices.py
- Scripts/DEADataHandling.py
- Scripts/README.rst
Moved TCI from DEADataHandling.py to BandIndices.py and used only one set of coefficients to calculate it. We are using landsat data that has been processed to surface reflectance so I've been using the Crist 85 coefficients, based off reflectance factors rather than top-off-atmosphere data. This change breaks one notebook that I know of.
> moving TCI to band indices and changing calculation

- Scripts/BandIndices.py
tasseled cap function was moved to BandIndices.py, but I forgot to add in the load statements for the dependencies.
> adding load modules to stop tasselled cap failing with no xarray

- Scripts/DEADataHandling.py
- Scripts/DEAPlotting.py
- Scripts/README.rst
New function for plotting an animated pixel drill next to an xarray time series; animation notebook updated to demo new functionality
Fixed bug #172 which caused errors if dimension names 'longitude', 'latitude' were used instead of 'x' and 'y'
> Add new animated_timeseriesline function and fix #172

- DEA_datasets/Introduction_to_Landsat.ipynb
Comments from @walsh-andrew from #154:
> The abbreviation "SR" is introduced in the NBAR-T section, but it is not defined (presumably 'surface reflectance'). SR can be defined on the first line of the document.
Just to make things easier to read, I've replaced all 'SR' with 'surface reflectance' 
> In the first notebook input cell (In [1]:), it says "Import dea-notebook functions. This assumes you are running this notebook from inside the dea-notebooks directory. If not, replace the relative ../Scripts link with a path to the dea-notebooks/Scripts directory. It is not clear how to find the dea-notebooks/Scripts directory. I just tried it with a notebook started using the DEA desktop icon and it still didn't work. So an explanation of starting a notebook from a subdirectory inside a cloned …
>  Revise Intro to Landsat notebook to close #154

- Temporal_analysis/Hovmoller_TCI_and_Rainfall.ipynb
Making only one top-level heading so that only the notebook title appears in the Table of Contents, here:
http://geoscienceaustralia.github.io/digitalearthau/notebooks/Temporal_analysis/README.html
> Fix heading for Hovmoller_TCI_and_Rainfall

- Temporal_analysis/Hovmoller_NDVI.ipynb
Making only one top-level heading so that only the notebook title appears in the Table of Contents, here:
http://geoscienceaustralia.github.io/digitalearthau/notebooks/Temporal_analysis/README.html
> Fix heading for Hovmoller NDVI

- 10_Scripts/DEADataHandling.py
- 10_Scripts/README.rst
Added a new function which allows you to load in data from both Sentinel 2A and 2B into a single dataset, and return only timesteps with more than xx% clear pixels (i.e. cloud-free timesteps).
This mimics the functionality that exists for `load_clearlandsat`.
> Add new load_clearsentinel function

- 10_Scripts/DEADataHandling.py
Added a new variable to `load_clearlandsat` and `load_clearsentinel2` that gives metadata on the satellite that took each observation:
```
:param satellite_metadata:
An boolean indicating whether to return the dataset with a `satellite` variable that gives the name of
the satellite that made each observation in the timeseries (i.e. ls5, ls7, ls8). Defaults to False.
```
Also added reproducible doctest example
> Add satellite metadata variable and add reproducible doctest to load_clearlandsat

- 10_Scripts/DEADataHandling.py
One last where statement snuck through the last update. Replaced with sel so that entire loaded data isn't coerced to float64 when removing Landsat SLC failed imagery.
> Fix remaining where statement to reduce memory usage when removing Landsat SLC failed

- 10_Scripts/README.rst
- 10_Scripts/RainfallTools.py
This script can be run to load the rainfall grids without the spatial offset problem.
> script to load rainfall without offset

- 10_Scripts/DEAPlotting.py
- 10_Scripts/README.rst
**New rgb function to replace three_band_image etc**
Currently we have a `three_band_image` and `three_band_image_subplots` functions in DEA Notebooks for plotting RGB images from xarray datasets. `three_band_image_subplots` does essentially the same thing as `three_band_image` except allows faceted plotting, however the function has been neglected for a while and produces pretty ugly outputs without a lot of fine-tuning (e.g. #248). Secondly, both functions essentially replicate functionality already available in xarray (e.g. RGB plotting with `plot.imshow()`), including faceted plots which are handled automatically (and far more nicely) via `col='time', col_wrap=2`
I propose changing to a simple function called `rgb` which serves as a wrapper around xarray's RGB plotting. For example, …
> New rgb and display map functions

- 10_Scripts/SpatialTools.py
Contour extract incorrectly applied the same x and y resolution offsets to contour points, instead of applying unique offsets for x and y. This produced an unexpected vertical offset because the y resolution was given a minus sign regardless of its correct value.
> Fix bug in contour_extract which vertically offset coordinates

- README.rst
replaced the link with a working link. As a side note, most of our readme doesn't show up in the read the docs - maybe we need to port some of it to the sub headings or speak to the restructured-text whisperers?
Bex
> Link to read the docs was broken

- 10_Scripts/SpatialTools.py
The geotransform function had mislabelled the pixel alignment parameter, and the comments have been tidied
> Tidying up geotransform function

- DEA_sandbox/Case_Studies/Coastal_Erosion.ipynb
- DEA_sandbox/Case_Studies/Intertidal_Elevation.ipynb
Duplicated info about choosing a new location, as several testers immediately chose a location outside of the extent of the available Landsat data.
Removed incorrect reference to Darwin tide post
Added warning that interactive map can take a while to load
> Update Coastal_Erosion text to clarify area/tide file selection

- DEA_sandbox/Case_Studies/utils/casestudy_agriculture_functions.py
- Use `.clear_output(wait=True)` to reduce flickering
- Disable map edit controls that user can not use: polyline and circlemarker
- Place plot to the right of the map
> Minor improvements to Agriculture Case Study app

- DEA_notebooks_template.ipynb
* Added a sentence pointing users to the `jupyterlab_code_formatter` (without making this compulsory)
* Moved instruction sentence about tags to the 'General advice' cell so users don't have to delete instructional text from multiple places in the notebook
* Added tags for NCI/sandbox compatibility: `:index:'sandbox_compatible', :index:'nci_compatible'`
> Add autoformatter details to template notebook and move tags info upward

- Scripts/dea_bandindices.py
- Scripts/dea_coastaltools.py
- Scripts/dea_datahandling.py
- Scripts/dea_plotting.py
- Scripts/dea_spatialtools.py
Committing first set of scripts for the `develop` branch, including the following functions:
- `load_ard`: a replacement for `load_clearlandsat` and `load_clearsentinel2` which combines multiple sensors, masks out cloud and optionally drops cloudy scenes. Should make it possible to load both Collection 3 Landsat and Sentinel 2 with the one function
- `rgb`: for RGB plotting
- `display_map`: for previewing a query before you load data
- `calculate_indices`: updated to include more indices, and to work on both Sentinel 2 and Landsat Collection 3
> Add initial set of scripts and funcs to `develop`

- 10_Scripts/DEADataHandling.py
By explicitely casting to `float32` before masking operations, we can avoid xarray automatically casting to more memory hungry `float64`.
> Fix load_clearlandsat casting to float64

- DEA_datasets/README.rst
- Frequently_used_code/README.rst
- Real_world_examples/README.rst
Adding some temporary information to the readme pages for each directory on `develop` to guide the creation of notebooks during the `dea-notebook` refresh
> Adding temporary info to `develop` readme pages

- Scripts/dea_datahandling.py
Due to a possible bug in recent `xarray` versions (> `v0.12.1`), changing the `dtype` of a dataset using `astype()` causes the dataset to lose its attributes like `.crs`. As a workaround, we now copy the attributes back into the dataset before subsequent steps.
This fix works on both `xarray` `v0.12.1` and `v0.12.3`.
> Fix load_ard to preserve attributes when masking

- 10_Scripts/DEADataHandling.py
Changes variable name in the case on single sensor for the load_clearlandsat() function.
- Closes Issue #377
> Fixes issue #377

- Scripts/dea_bandindices.py
Adds an additional preset variable into the calculate_indices script `drop` which when set to True, drops input bands, saving memory. default behaviour is `False`
-mentioned in issue #375
> added ability to drop bands into the bandindices script

- Scripts/dea_datahandling.py
Moving `wofs_fuser` to `dea_datahandling` to remove dependency on the `digitalearthau` module
Minor formatting change in header of script
> Add wofs_fuser to dea_datahandling

- Scripts/dea_datahandling.py
The previous addition of `wofs_fuser` broke `dea_datahandling` because of an incorrect indent. My fault for not testing this!
> Fix indent error in `dea_datahandling`

- Frequently_used_code/virtual-product-catalog.yaml
- Supersedes PR #408 
- Add example virtual products notebook to `Frequently_used_code`
- Apologies as I could not figure out how to break this into self-contained little pieces
- The `datacube-core` version can be updated in the Sandbox by cloning it and running `pip install --user .`
- Native English speakers feel free to suggest grammar/flow changes
> Virtual products notebook

- DEA_notebooks_template.ipynb
I've made some minor updates to the notebook template based on my experiences using it over the past few weeks. These are completely optional, I just wanted to start the discussion with a pull request so we have something to work from!
1. I've moved the Guidance cell to the very top of the notebook so it's easier to delete
2. I've got rid of the `Analyses used` bullet point, as I found this a bit redundant. Details on analyses included in the notebook could instead be included as a numbered list in the `Description` section (like most notebooks already do).
3. In addition to the above, moved the `Products used` and `Special requirements` bullet points right up to the top next to the `Compatible with...` statement. That way all the important stuff is at the top.
4. Updated the tags to …
> Update to notebook template after refresh sprint

- DEA_notebooks_template.ipynb
Made some minor style updates for compatability with the new beginners guide notebooks.
Also fixed up some issues that are affecting correct rendering on the readthedocs page (headings order, spaces between bullet points and text, multiple formatting types).
Finally, re-wrote some of the instructional code so that it makes sense even if the text is left in the notebook rather than removed (as happens reasonably regularly.
> Minor style updates and fixes for readthedocs issues

- Scripts/dea_datahandling.py
Added a User Warning to `load_ard` to inform the user that setting min_goodata to >0.0 will result in dask_arrays computing during the step where the percentage good data is calculatedp. This can significantly slow down your code / use up lots of memory when trying to lazy load a large dataset.
> adding Dask-related UserWarning to load_ard

- Scripts/dea_spatialtools.py
Have added a new function to identify the largest connected area of pixels within an xarray dataset. This can be used for e.g. selecting the largest waterbody in an array, for example for separating ocean pixels from inland pixels.
> Add largest_region function to dea_spatialtools

- Scripts/dea_classificationtools.py
The new `get_training_data_for_shp` function in the `dea_classificationtools` module (see #443) extracts data for all pixels for every feature in a shapefile. This adds the option to calculate summary statistics for the feature as well. Currently supports:
* mean
* geomedian (using `hdstats.geomedian`)
I've added the `hdstats` import to within the function it is used so it isn't a dependency for the whole module but can move to top if preferred.
Tested on AWS sandbox.
> Added option in classification tools to use hdstats.geomedian

- README.rst
Added link to wiki to `develop` readme to make it easier for users to find guides for getting started with the Sandbox/NCI.
> Add link to wiki getting started guides to readme

- Frequently_used_code/README.rst
Kirill's notebook was missing from the index and not rendered in the docs
Imagery_on_web_map.ipynb
> Add missing Imagery_on_web_map.ipynb notebook to index

- LICENSE
- README.rst
We mention that we use the Apache License Version 2.0 throughout the repo, but we don't actually include the license file/text anywhere. This should officially add it!
> Officially add license to repo

- Scripts/dea_datahandling.py
@lauragow picked up an issue with the `load_ard` function where the function failed when no `measurements` were specified. This was caused by Sentinel-2 and Landsat ARD data loading ancillary variables (e.g. fmask, contiguity) with different names by if no measurements are specified:
- Landsat: `oa_variable_name`
- Sentinel-2: `variable_name`
To fix this, I've added a test at the beginning to test whether the user is loading Landsat or Sentinel-2 data. Hopefully a future Sentinel-2 collection upgrade will make the variable names consistent!
- Closes Issue #496
> Fix #496 issue with load_ard

- Scripts/dea_plotting.py
Small change to allow `rgb` to be supplied with a custom matplotlib `ax` object for custom plotting (e.g. inserting into a subplot).
The function now ignores the `aspect` and `size` params if a custom `ax` is supplied.
> Allow rgb function to be supplied with an `ax` matplotlib object for plotting

- Frequently_used_code/Image_segmentation.ipynb
Fix error in `Image_segmentation.ipynb` one of the output files was named with `.tif` but was populated by `rsgislib` with KEA format, `rsgislib` would then fail to open the file it produced to add statistics and overviews to it. Changing file name to end on `.kea` fixes the problem. 
This was tested in the sandbox using custom docker with `rsgislib` installed, this docker is not yet available to sandbox users.
> Fix image segmentation notebook

- Scripts/dea_spatialtools.py
Call to `datacube.utils.geometry` routines for transforming geometries from one projection to another.
- Closes Issue #522
> Use datacube.utils.geom tools in transform_geojson_wgs_to_epsg

- Scripts/dea_datahandling.py
This update restores lazy loading functionality to `load_ard`, so that datasets are filtered/observations dropped based on `min_gooddata` before the data is loaded into memory, not after.
This greatly reduces the load time of any notebook that uses the `min_gooddata` parameter to load non-cloudy observations.
- Closes Issue #520
> Restore lazy load to load_ard

- Scripts/dea_plotting.py
The `rgb` function can plot improper aspects if data data is loaded with an unexpected dimension order, which caused time to be used instead of longitude when calculating the image aspect.
Have replaced the existing code with from `odc.ui import image_aspect` which is more resilient to dimension order.
See https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/issues/54
> Calculate `rgb` aspect using `odc.ui` tools

- Scripts/dea_spatialtools.py
Issue #539 occurred when `subpixel_contours` was applied to an xarray dataset loaded using `xr.open_rasterio`. The problem is related to the current overly complex way `multiple z-value, single array mode` is implemented in `subpixel_contours`:
- Currently, a 2D array is converted to 3D by adding a new `z_value` dimension. This needlessly duplicates the data, and causes strange interactions with `scikit-image` as found in #539.
- This fix simplifies the approach to simply iterate through the list of `z_values`, rather than expand any dimensions. This fixes the  `ValueError: buffer source array is read-only` error.
- Closes Issue #539
> Fix #539 by simplifying multiple z-value, single array mode in `subpixel_contours`

- Scripts/dea_spatialtools.py
`crs` is defined in the function a few lines above as a crs object.
Later on it then takes this as a string and tries to feed it into the `{'init:(crs)}` format, but this errors because the crs is not just an EPSG number.
> Fix possible bug in subpixel_contours

- Scripts/dea_dask.py
- Enable dashboard link via proxy if `jupyter-server-proxy` is install regardless of the `AWS_`  environment variables. This should also be useful for people on NCI who access via ssh port forwarding.
- White space cleanups
- Remove `client` deletion from `locals()` this is always no-op in a function
- Closes Issue #554
> Fix dask dashboard link

- Scripts/dea_spatialtools.py
Issue #590 gives an example where `subpixel_contours` does not raise an exception when no valid contours are returned, despite an exception being raised when a `output_path` is supplied. 
This PR updates the function to do two things:
1. Always raise an exception if _all_ contours fail
2. _Optionally_ raise an exception if _any_ contours fail
Option 2 is controlled by a new `errors` parameter, which either prints failed contours to the console, or raises an error:
```
errors : string, optional
If 'raise', then any failed contours will raise an exception.
If 'ignore' (the default), a list of failed contours will be 
printed. If no contours are returned, an exception will always 
be raised.
```
- Closes Issue #590
> Add exception handling for `subpixel_contours` when some or all contours fail 

- Scripts/dea_plotting.py
Closes issue #486 by removing the depreciated "init" prefix for Proj in `display_map`.
> Close #486 by removing 'init' from Proj call

- README.rst
It's now been six months since the DEA Notebooks refresh, I think this text at the top of the repository readme file can be removed
> Retire DEA Notebooks refresh header text

- Scripts/dea_spatialtools.py
Fix undefined variable reference. 
- Closes Issue #000
- Closes Issue #000
> Fix export_tiff case in xr_rasterise

- Scripts/dea_plotting.py
@andrewdhicks found a bug in DEAfrica where the `rgb` function makes multiple passes over the same data when using `dask` when `robust=True` to internally calculate the 2 and 98 percentiles:
https://github.com/digitalearthafrica/deafrica-sandbox-notebooks/issues/141#issue-664126942
This PR fixes this issue by specifically computing the array of data to be plotted earlier in the process, so the percentile calculation does not need to compute it a second time.
> Prevent `rgb` from doing multiple dask computes over the same data

- Scientific_workflows/DEAWaterbodies/DEAWaterbodiesToolkit/ENSOInfluence.ipynb
Added notebook that estimates ENSO influence on DEA Waterbodies.
> Added ENSO influence waterbodies notebook

- Scripts/dea_classificationtools.py
The `collect_training_data` function has a hard-coded 'EPSG:3577' `crs` when extracting geometries for querying the datacube, when the `crs` on the shapefile doesn't match 3577, `load_ard` fails to find data.  This fix uses the shapefile's `crs` to query the datacube.
> Fix hard-coded CRS

- Scripts/dea_plotting.py
Lan-Wei encountered a nasty issue where one-band animations were being plotted with unexpected colours that did not match the underlying data when using the default `percentile_clip`. This revealed that the animation code was inadvertently plotting colour stretches for each frame independently, which meant strictly that animation frames could not be compared fairly across time. This was not noticed up to now as most animations are based on multi-band satellite data with approximately similar distributions in each frame - Lan-Wei's example involved plotting single-band timesteps with a single unique value in each frame, which made the scaling issue much more obvious.
A secondary issue involved a scenario where the user manually specifies a `vmin` and `vmax` used to scale colours. As part …
> Fix major scaling bug in xr_animation, remove deprecated funcs

- Scripts/dea_spatialtools.py
Non-specific exceptions are hard (read: not really possible) to catch, and therefore discouraged in Python. I've changed all the `Exception`s in `subpixel_contours` to `ValueError`, `TypeError`, or `RuntimeError` as most appropriate. I also made it so that no-contours doesn't raise an error unless `errors="raise"`.
> Made exceptions more specific in subpixel_contours

- Scripts/dea_spatialtools.py
This adds some verbose flags and more specific exceptions to the other major functions in `dea_spatialtools`, which I did for `subpixel_contours` in #657 and #654 but didn't realise needed to be done for the other functions too. The final three functions seemed OK without a flag. `xr_vectorize` doesn't use the verbose flag as it stands but I've included one for API consistency.
> Added verbose flags and different exceptions to spatialtools

- Supplementary_data/Virtual_products/virtual-product-catalog.yaml
Showcase virtual product transforms that can be defined in the catalog YAML.
> virtual product transform updates

- Real_world_examples/Estimate_climate_driver_influence_on_rainfall.ipynb
- Real_world_examples/README.rst
Added a notebook that estimates climate driver influence on rainfall. I want to use this as a comparison for doing the same thing with waterbodies, since the behaviour of rainfall is better understood than the behaviour of wet surface area.
> Added climate driver notebook
